version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend/sessions:/app/sessions
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JWT_SECRET=rahasia

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
